# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NameService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11NameService.proto\x12\x0cname_service\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"9\n\nServerData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\"\x1a\n\nServerName\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\rEmployeeTitle\x12\r\n\x05title\x18\x01 \x01(\t2\xe7\x01\n\x0bNameService\x12G\n\x0eRegisterServer\x12\x18.name_service.ServerData\x1a\x19.name_service.StatusReply\"\x00\x12I\n\x10UnregisterServer\x12\x18.name_service.ServerName\x1a\x19.name_service.StatusReply\"\x00\x12\x44\n\x0cLookupServer\x12\x18.name_service.ServerName\x1a\x18.name_service.ServerData\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NameService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _globals['_STATUSREPLY']._serialized_start=35
  _globals['_STATUSREPLY']._serialized_end=64
  _globals['_SERVERDATA']._serialized_start=66
  _globals['_SERVERDATA']._serialized_end=123
  _globals['_SERVERNAME']._serialized_start=125
  _globals['_SERVERNAME']._serialized_end=151
  _globals['_EMPLOYEETITLE']._serialized_start=153
  _globals['_EMPLOYEETITLE']._serialized_end=183
  _globals['_NAMESERVICE']._serialized_start=186
  _globals['_NAMESERVICE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
